# Generated by Django 3.2.9 on 2022-11-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_master_type_reair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typerepair',
            old_name='name_1',
            new_name='name',
        ),
    ]
