# Generated by Django 3.2.9 on 2022-11-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_name_1_typerepair_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.typerepair'),
        ),
    ]
