# Generated by Django 3.2.9 on 2022-11-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_task_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='organization_other',
        ),
        migrations.RemoveField(
            model_name='completedtask',
            name='video_2',
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.allobjects'),
            preserve_default=False,
        ),
    ]
