# Generated by Django 3.2.9 on 2022-11-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20221125_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.allobjects'),
        ),
    ]
