# Generated by Django 3.2.9 on 2022-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_completedtask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/files'),
        ),
    ]
