# Generated by Django 3.2.9 on 2022-11-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20221125_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.allobjects'),
        ),
    ]
