# Generated by Django 3.2.9 on 2022-11-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_completedtask_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.allobjects'),
        ),
        migrations.AlterField(
            model_name='task',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.typerepair'),
        ),
    ]
